=== eddeighton/eg/src/schema/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (x64) (http://www.altova.com) by Edward Deighton (Deighton Systems Limited) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="eg">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="host" type="xs:string"/>
				<xs:element name="folder" type="xs:string"/>
				<xs:element name="stuff" type="Config" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Config">
		<xs:sequence>
			<xs:element name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="file" type="xs:boolean" nillable="false"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== eddeighton/eg/src/schema/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<eg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///W:/workspace/eg/src/schema/schema.xsd">
	<host>test</host>
	<folder>theFolder</folder>
	<stuff>
		<name>test1</name>
		<file>true</file>
	</stuff>
	<stuff>
		<name>test2</name>
		<file>false</file>
	</stuff>
</eg>
